### ISSUE TITLE
Display user profile info card when hovering on user

### ISSUE THREAD

**Issue by dubeaud** [dubeaud/bugnet#64]
Also it would be nice if all information about a user would be shown when you put your mouse over their name while viewing a issue.

**Comment by ericthornton** [comment]
@dubeaud I see the reference to the original request, but I'm curious where this is really meant to apply? In viewing the issue details? Because that's just a dropdown for the users -- hovering over the dropdown would invoke this? Or is it in the list of issues when you hover their name? 

I wanted to see your preference before I started any work on it.

**Comment by dubeaud** [comment]
I would assume it would be like stack overflow etc where you hover over the name. This probably would only happen on comments and the issue list.
