### ISSUE TITLE
Automatically convert bug number into link

### ISSUE THREAD

**Issue by dubeaud** [dubeaud/bugnet#9]
**This issue was imported from [CodePlex](http://bugnet.codeplex.com/workitem/139)**

**[bobpy2k](http://www.codeplex.com/site/users/view/bobpy2k)** wrote 2013-08-30 at 06:33
When listing the ID of another issue in the description of one, could this not be automatically turned into a link?

Similar to the use of related issues, but automated.

**Comment by kalkie** [comment]
Hi Davin,

I was thinking about helping to implement this feature in bugnet. Do you already have an idea on how this functionality should work? I was thinking to implement it in the following matter:

If in the description of an issue the project code is reference together with the issue number separated by a dash (for example "ProjectABC-15") it gets converted into an hyperlink that links to the issue detail page (IssueDetail.aspx?id=15)  
The conversion is done in real-time when the issue is shown on screen, the link does not get stored in the database.

Any thoughts?

**Comment by dubeaud** [comment]
I think that sounds like a good idea.  I do something similar with the wiki feature in the pro version.  Here is the code for that if you find it useful

// usage
[issue:_issue id_]
[issue:Friendly Text|_issue id_]

```csharp

string id = input.Substring(input.LastIndexOf("-") + 1);
            Issue issue = IssueManager.GetById(Convert.ToInt32(id));

            if(issue != null)
            {
                if (input.Contains("|"))
                {
                    title = input.Substring(input.LastIndexOf(":") + 1, (input.LastIndexOf("|") - 1) - input.LastIndexOf(":"));
                }
                else
                {
                     title = issue.Title;
                }
            }
            else
            {
                return "<span class=\"unresolved\">Cannot resolve issue macro, invalid id.</span>";
            }
             
            string url = System.Web.VirtualPathUtility.ToAbsolute("~/Issues/IssueDetail.aspx?id=" + id);
            return string.Format(LinkFormat, attributeEncode(url), htmlEncode(title));
```

**Comment by elbaloo** [comment]
Seems like this can be closed now.
